---
- hosts: devops
  user: sre
  become: yes
  connection: ssh
  tasks:
    - name: install httpd
      command: yum install httpd -y
    - name: start httpd service
      command: sudo systemctl start httpd
    - name: httpd service status
      command: sudo systemctl status httpd
